version: '3.8'

services:
  # Frontend (React/Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Exposing the frontend on port 8080
    volumes:
      - ./frontend:/app
    depends_on:
      - backend  # Ensure backend is ready before frontend starts
    environment:
      VITE_BACKEND_URL: "http://backend:8000"  # Assuming backend runs on port 8000 in the container

  # Backend (Laravel)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Exposing the backend on port 8000
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: production
      APP_URL: http://backend:8000  # Backend URL
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite  # SQLite path inside container
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
